config/routes.rb
Plants::Application.routes.draw do

  root :to => 'root#index'

  get 'profile' => 'profile#me'
  get 'profile/member'
  get 'profile/catalog'
  put 'profile/update_member'
  post 'profile/update_member'
  put 'profile/update_me'
  post 'profile/update_me'
  get 'profile/new_price'
  put 'profile/save_price'
  post 'profile/save_price'
  put 'profile/update_plant_price'
  post 'profile/update_plant_price'
  post 'profile/remove_plant_price'
  delete 'profile/remove_member_price'

  devise_for :users, :path => "auth", :path_names => {:sign_in => 'login',
                                                      :sign_out => 'logout',
                                                      :password => 'secret',
                                                      :confirmation => 'verification',
                                                      :unlock => 'unblock',
                                                      :registration => 'register',
                                                      :sign_up => 'cmon_let_me_in'},
             :controllers => {:registrations => "registrations"}


  resources :members
  resources :plants
  resources :images

  namespace :control do

    root :to => 'users#index'

    resources :members
    resources :plants
    resources :users
    resources :member_categories
    resources :regions
    resources :countries
    resources :plant_categories
    resources :plant_features
    resources :genus
  end

end

app/models/plant.rb
#encoding: UTF-8
class Plant < ActiveRecord::Base

  belongs_to :plant
  belongs_to :genu
  belongs_to :plant_category
  has_many :images, :foreign_key => :owner_id, :dependent => :destroy
  has_many :plant_prices, :dependent => :destroy

  scope :moderated, lambda { where(:enabled => true) }
  scope :only_parents, lambda { where(:plant_id => nil) }

  attr_accessible :description, :description_short, :application, :height, :lat_name, :name, :width, :plant_id,
                  :crown, :leaves, :flowers, :genu_id, :plant_category_id
  attr_accessible :synonyms, :lat_synonyms
  attr_accessible :enabled

  validates :name, :lat_name, :presence => true, :uniqueness => true

  def title
    "#{self.lat_name} (#{self.name})"
  end

end

app/controllers/control/plants_controller.rb
module Control
  class PlantsController < ControlPanelController

    after_filter :update_plant_images, :only => [:create, :update]

    # GET /plants
    # GET /plants.json
    def index

      @plants = Plant.order("#{sort_column} #{sort_direction}")
      unless params[:name].blank?
        name_query = "%#{params[:name]}%"
        @plants = @plants.where('name LIKE ? OR lat_name LIKE ?', name_query, name_query)
      end
      unless params[:genu_id].blank?
        @plants = @plants.only_parents.where(:genu_id => params[:genu_id])
      end
      unless params[:plant_category_id].blank?
        @plants = @plants.where(:plant_category_id => params[:plant_category_id])
      end
      @plants = @plants.paginate(:page => params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @plants }
      end
    end

    # GET /plants/1
    # GET /plants/1.json
    def show
      @plant = Plant.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @plant }
      end
    end

    # GET /plants/new
    # GET /plants/new.json
    def new
      @plant = Plant.new(:plant_category_id => params[:plant_category_id],
                         :genu_id => params[:genu_id],
                         :plant_id => params[:plant_id])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @plant }
      end
    end

    # GET /plants/1/edit
    def edit
      @plant = Plant.find(params[:id])
    end

    # POST /plants
    # POST /plants.json
    def create
      @plant = Plant.new(params[:plant])

      respond_to do |format|
        if @plant.save
          format.html { redirect_to control_plants_path,
                                    notice: t('activerecord.attributes.plant.messages.has_been_success_created') }
          format.json { render json: @plant, status: :created, location: @plant }
        else
          format.html { render action: "new" }
          format.json { render json: @plant.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /plants/1
    # PUT /plants/1.json
    def update
      @plant = Plant.find(params[:id])

      respond_to do |format|
        if @plant.update_attributes(params[:plant])
          format.html { redirect_to control_plants_path,
                                    notice: t('activerecord.attributes.plant.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @plant.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /plants/1
    # DELETE /plants/1.json
    def destroy
      @plant = Plant.find(params[:id])
      @plant.destroy

      respond_to do |format|
        format.html { redirect_to control_plants_path }
        format.json { head :no_content }
      end
    end

    private

    def update_plant_images
      return if params[:images].blank?
      params[:images].each do |image|
        image = Image.find(image.last.to_i)
        image.owner_id = @plant.id
        image.save
      end
    end

  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index

    respond_to do |format|
      format.html {

        @genus = Genu.order

        unless params[:genu_id].blank?
          @genus = @genus.where(:id => params[:genu_id])
        end

        unless params[:search].blank?
          search_string = "%#{params[:search]}%"
          @genus = @genus.joins(:plants)
          .where('genus.name LIKE ? OR genus.lat_name LIKE ? OR plants.name LIKE ? OR plants.lat_name LIKE ?',
                 search_string, search_string, search_string, search_string)
          .group('genus.id')
        end

        @genus = @genus.paginate(:page => params[:page])

      }
      format.json {

        render json: Plant.all
      }
    end


  end

  def show
    @plant = Plant.find(params[:id])
  end

end

app/helpers/plants_helper.rb
#encoding: UTF-8
module PlantsHelper

  def plant_value_or_na(value)

    return 'н/а' if value.blank?
    value

  end

end

app/views/plants/index.html.slim
= content_for :search do
  form action=(plants_path) method="get"
    .well.sidebar-nav style="margin-top: 90px;"
      ul.nav.nav-list
        li.nav-header Поиск
        li
          p
            = text_field_tag :search, params[:search], :placeholder => 'Название'
        li
          p
            span Род:
            br
            = select_tag :genu_id, options_from_collection_for_select(Genu.all, :id, :name, params[:genu_id]), :prompt => 'Все'
        li
          = submit_tag 'Поиск', :class => 'btn btn-primary', :name => nil
          = button_tag 'Сбросить', :class => 'btn', :name => nil, :type => 'reset'
h1 Растения
#plants
  - if @genus.empty?
    p Поиск не дал результатов, попробуйте выбрать другие критерии поиска.
  - @genus.each do |genu|
    .plant-item
      h4= genu.title
      .description
        = genu.description
      .kinds
        ul
          - genu.plants.only_parents.each do |kind|
            li
              .kind
                h5 style="background-color: #f2f2f2; padding: 5px; border-radius: 3px;"
                  = link_to kind.title, plant_path(kind), :target => '_blank'
                .description
                  = kind.description
                .kind-images
                  - kind.images.each do |image|
                    a href="javascript: showPlantFullImage('#{image.picture(:medium)}')"
                      = image_tag (image.picture(:mini_thumb))
                .kind-info
                  .param
                    span.name Высота:
                    = plant_value_or_na(kind.height)
                  .param
                    span.name Ширина:
                    = plant_value_or_na(kind.width)
                  .param
                    span.name Крона:
                    = plant_value_or_na(kind.crown)
                  .param
                    span.name Цветы:
                    = plant_value_or_na(kind.flowers)
                  .param
                    span.name Листья:
                    = plant_value_or_na(kind.leaves)
                div style="clear: both;"
                hr
                .sorts
                  ul
                    - Plant.where(:plant_id => kind.id).each do |sort|
                      li
                        .sort
                          = link_to sort.title, plant_path(sort), :target => '_blank'
                          table
                            tr
                              td
                                - sort_image = sort.images.first
                                a href="javascript: showPlantFullImage('#{sort_image.picture(:medium)}')"
                                  = image_tag(sort_image.picture(:mini_thumb))
                              td
                                .sort-info
                                  .param
                                    span.name Высота:
                                    = plant_value_or_na(sort.height)
                                  .param
                                    span.name Ширина:
                                    = plant_value_or_na(sort.width)
                                  .param
                                    span.name Крона:
                                    = plant_value_or_na(sort.krone)
                                  .param
                                    span.name Цветы:
                                    = plant_value_or_na(sort.flowers)
                                  .param
                                    span.name Листья:
                                    = plant_value_or_na(sort.leafs)
                          div style="clear: both;"
                          hr
  = will_paginate @genus, :renderer => BootstrapPagination::Rails

app/views/plants/show.html.slim
#plant
  h1= @plant.title
  hr
  h5 Описание
  .plant-info
    .param
      span.name Высота:
      = plant_value_or_na(@plant.height)
    .param
      span.name Ширина:
      = plant_value_or_na(@plant.width)
    .param
      span.name Крона:
      = plant_value_or_na(@plant.crown)
    .param
      span.name Цветы:
      = plant_value_or_na(@plant.flowers)
    .param
      span.name Листья:
      = plant_value_or_na(@plant.leaves)
  div style="clear: both;"
  hr
  h5 Фотографии
  .plant-images
    - @plant.images.each do |image|
      a href="javascript: showPlantFullImage('#{image.picture(:medium)}')"
        = image_tag (image.picture(:thumb))