config/routes.rb
Plants::Application.routes.draw do

  root :to => 'root#index'

  get 'profile' => 'profile#me'
  get 'profile/member'
  get 'profile/catalog'
  put 'profile/update_member'
  post 'profile/update_member'
  put 'profile/update_me'
  post 'profile/update_me'
  get 'profile/new_price'
  put 'profile/save_price'
  post 'profile/save_price'
  put 'profile/update_plant_price'
  post 'profile/update_plant_price'
  post 'profile/remove_plant_price'
  delete 'profile/remove_member_price'

  devise_for :users, :path => "auth", :path_names => {:sign_in => 'login',
                                                      :sign_out => 'logout',
                                                      :password => 'secret',
                                                      :confirmation => 'verification',
                                                      :unlock => 'unblock',
                                                      :registration => 'register',
                                                      :sign_up => 'cmon_let_me_in'},
             :controllers => {:registrations => "registrations"}


  resources :members
  resources :plants
  resources :images

  namespace :control do

    root :to => 'users#index'

    resources :members
    resources :plants
    resources :users
    resources :member_categories
    resources :regions
    resources :countries
    resources :plant_categories
    resources :plant_features
    resources :genus
  end

end

app/controllers/control/countries_controller.rb
module Control
  class CountriesController < ControlPanelController
    # GET /countries
    # GET /countries.json
    def index
      @countries = Country.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @countries }
      end
    end

    # GET /countries/1
    # GET /countries/1.json
    def show
      @country = Country.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @country }
      end
    end

    # GET /countries/new
    # GET /countries/new.json
    def new
      @country = Country.new

      respond_to do |format|
        format.html { render :layout => !request.xhr? } # new.html.erb
        format.json { render json: @country }
      end
    end

    # GET /countries/1/edit
    def edit
      @country = Country.find(params[:id])
    end

    # POST /countries
    # POST /countries.json
    def create
      @country = Country.new(params[:country])

      respond_to do |format|
        if @country.save
          format.html { redirect_to control_countries_path,
                                    notice: t('activerecord.attributes.country.messages.has_been_success_created') }
          format.json { render json: @country, status: :created, location: @country }
        else
          format.html { render action: "new" }
          format.json { render json: @country.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /countries/1
    # PUT /countries/1.json
    def update
      @country = Country.find(params[:id])

      respond_to do |format|
        if @country.update_attributes(params[:country])
          format.html { redirect_to control_countries_path,
                                    notice: t('activerecord.attributes.country.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @country.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /countries/1
    # DELETE /countries/1.json
    def destroy
      @country = Country.find(params[:id])
      @country.destroy

      respond_to do |format|
        format.html { redirect_to control_countries_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/control/genus_controller.rb
module Control
  class GenusController < ControlPanelController

    # GET /genus
    # GET /genus.json
    def index

      @genus = Genu.order("#{sort_column} #{sort_direction}")
      if params[:category_id]
        @genus = @genus.where(:plant_category_id => params[:category_id])
      end
      @genus = @genus.paginate(:page => params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @genus }
      end

    end

    # GET /genus/new
    # GET /genus/new.json
    def new
      @genu = Genu.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @genu }
      end
    end

    # GET /genus/1/edit
    def edit
      @genu = Genu.find(params[:id])
    end

    # POST /genus
    # POST /genus.json
    def create

      @genu = Genu.new(params[:genu])

      respond_to do |format|
        if @genu.save
          format.html { redirect_to control_genus_path,
                                    notice: t('activerecord.attributes.genu.messages.has_been_success_created') }
          format.json { render json: @genu, status: :created, location: @genu }
        else
          format.html { render action: "new" }
          format.json { render json: @genu.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /genus/1
    # PUT /genus/1.json
    def update
      @genu = Genu.find(params[:id])

      respond_to do |format|
        if @genu.update_attributes(params[:genu])
          format.html { redirect_to control_genus_path,
                                    notice: t('activerecord.attributes.genu.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @genu.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /genus/1
    # DELETE /genus/1.json
    def destroy
      @genu = Genu.find(params[:id])
      @genu.destroy

      respond_to do |format|
        format.html { redirect_to control_genus_path }
        format.json { head :no_content }
      end
    end

  end
end

app/controllers/control/member_categories_controller.rb
module Control
  class MemberCategoriesController < ControlPanelController
    # GET /member_categories
    # GET /member_categories.json
    def index
      @member_categories = MemberCategory.order("#{sort_column} #{sort_direction}")

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @member_categories }
      end
    end

    # GET /member_categories/1
    # GET /member_categories/1.json
    def show
      @member_category = MemberCategory.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @member_category }
      end
    end

    # GET /member_categories/new
    # GET /member_categories/new.json
    def new
      @member_category = MemberCategory.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @member_category }
      end
    end

    # GET /member_categories/1/edit
    def edit
      @member_category = MemberCategory.find(params[:id])
    end

    # POST /member_categories
    # POST /member_categories.json
    def create
      @member_category = MemberCategory.new(params[:member_category])

      respond_to do |format|
        if @member_category.save
          format.html { redirect_to control_member_categories_path,
                                    notice: t('activerecord.attributes.member_category.messages.has_been_success_created') }
          format.json { render json: @member_category, status: :created, location: @member_category }
        else
          format.html { render action: "new" }
          format.json { render json: @member_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /member_categories/1
    # PUT /member_categories/1.json
    def update
      @member_category = MemberCategory.find(params[:id])

      respond_to do |format|
        if @member_category.update_attributes(params[:member_category])
          format.html { redirect_to control_member_categories_path,
                                    notice: t('activerecord.attributes.member_category.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @member_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /member_categories/1
    # DELETE /member_categories/1.json
    def destroy
      @member_category = MemberCategory.find(params[:id])
      @member_category.destroy

      respond_to do |format|
        format.html { redirect_to control_member_categories_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/control/members_controller.rb
module Control
  class MembersController < ControlPanelController

    after_filter :update_member_logo, :only => [:create, :update]

    # GET /members
    # GET /members.json
    def index
      @members = Member.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @members }
      end
    end

    # GET /members/1
    # GET /members/1.json


    # GET /members/new
    # GET /members/new.json
    def new
      @member = Member.new
      @member.regions.build

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @member }
      end
    end

    # GET /members/1/edit
    def edit
      @member = Member.find(params[:id])
    end

    # POST /members
    # POST /members.json
    def create

      @member = Member.new(params[:member])

      respond_to do |format|
        if @member.save
          format.html { redirect_to control_members_path,
                                    notice: t('activerecord.attributes.member.messages.has_been_success_created') }
          format.json { render json: @member, status: :created, location: @member }
        else
          format.html { render action: "new" }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /members/1
    # PUT /members/1.json
    def update

      @member = Member.find(params[:id])

      respond_to do |format|
        if @member.update_attributes(params[:member])
          format.html { redirect_to control_members_path,
                                    notice: t('activerecord.attributes.member.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /members/1
    # DELETE /members/1.json
    def destroy
      @member = Member.find(params[:id])
      @member.destroy

      respond_to do |format|
        format.html { redirect_to control_members_path }
        format.json { head :no_content }
      end
    end

    private

    def update_member_logo
      return if params[:logo_id].blank?

      old_images = Image.where(:owner_id => @member.id)
      old_images.delete_all

      image = Image.find(params[:logo_id])
      image.owner_id = @member.id
      image.save
    end

  end
end

app/controllers/control/plant_categories_controller.rb
module Control
  class PlantCategoriesController < ControlPanelController
    # GET /plant_categories
    # GET /plant_categories.json
    def index

      case params[:filter]
        when 'category' then

          @plant_categories = []

          category = PlantCategory.find(params[:id])
          @plant_categories << category
          until category.plant_category_id.nil?
            category = PlantCategory.find(category.plant_category_id)
            @plant_categories << category
          end
          @plant_categories.reverse!

        when 'parent' then
          @plant_categories = PlantCategory.where(:parent_category_id => params[:id])
        else
          @plant_categories = PlantCategory.order("#{sort_column} #{sort_direction}").make_categories_tree_hash
      end

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @plant_categories }
      end

    end

    # GET /plant_categories/1
    # GET /plant_categories/1.json
    def show
      @plant_category = PlantCategory.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @plant_category }
      end
    end

    # GET /plant_categories/new
    # GET /plant_categories/new.json
    def new
      @plant_category = PlantCategory.new(:parent_category_id => params[:parent_category_id])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @plant_category }
      end
    end

    # GET /plant_categories/1/edit
    def edit
      @plant_category = PlantCategory.find(params[:id])
    end

    # POST /plant_categories
    # POST /plant_categories.json
    def create
      @plant_category = PlantCategory.new(params[:plant_category])

      respond_to do |format|
        if @plant_category.save
          format.html { redirect_to control_plant_categories_path,
                                    notice: t('activerecord.attributes.plant_category.messages.has_been_success_created') }
          format.json { render json: @plant_category, status: :created, location: @plant_category }
        else
          format.html { render action: "new" }
          format.json { render json: @plant_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /plant_categories/1
    # PUT /plant_categories/1.json
    def update
      @plant_category = PlantCategory.find(params[:id])

      respond_to do |format|
        if @plant_category.update_attributes(params[:plant_category])
          format.html { redirect_to control_plant_categories_path,
                                    notice: t('activerecord.attributes.plant_category.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @plant_category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /plant_categories/1
    # DELETE /plant_categories/1.json
    def destroy
      @plant_category = PlantCategory.find(params[:id])
      @plant_category.destroy

      respond_to do |format|
        format.html { redirect_to control_plant_categories_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/control/regions_controller.rb
module Control
  class RegionsController < ControlPanelController

    before_filter :login_required, :except => :index

    # GET /regions
    # GET /regions.json
    def index

      @regions = Region.order("#{sort_column} #{sort_direction}")
      if params[:country_id]
        @regions = @regions.where(:country_id => params[:country_id])
      end
      @regions = @regions.paginate(:page => params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @regions }
      end
    end

    # GET /regions/1
    # GET /regions/1.json
    def show
      @region = Region.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @region }
      end
    end

    # GET /regions/new
    # GET /regions/new.json
    def new
      @region = Region.new(:country_id => params[:country_id])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @region }
      end
    end

    # GET /regions/1/edit
    def edit
      @region = Region.find(params[:id])
    end

    # POST /regions
    # POST /regions.json
    def create
      @region = Region.new(params[:region])

      respond_to do |format|
        if @region.save
          format.html { redirect_to control_regions_path,
                                    notice: t('activerecord.attributes.region.messages.has_been_success_created') }
          format.json { render json: @region, status: :created, location: @region }
        else
          format.html { render action: "new" }
          format.json { render json: @region.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /regions/1
    # PUT /regions/1.json
    def update
      @region = Region.find(params[:id])

      respond_to do |format|
        if @region.update_attributes(params[:region])
          format.html { redirect_to control_regions_path,
                                    notice: t('activerecord.attributes.region.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @region.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /regions/1
    # DELETE /regions/1.json
    def destroy
      @region = Region.find(params[:id])
      @region.destroy

      respond_to do |format|
        format.html { redirect_to control_regions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper

  def member_title(member)
    title = member.name
    member.member_categories.each do |c|
      title += ", #{c.name}"
    end
    title
  end

  def categories_string(member)
    categories = ''
    member.member_categories.each do |c|
      categories += " #{c.name},"
    end
    categories.chop
  end

end

app/views/control/members/_address.html.slim
.address
  .address-title
    a#title href="javascript:" onclick="AddressDialog.show($(this).parents('.address').first())"
      = f.object.address
    = f.link_to_remove 'Удалить', :class => 'btn btn-danger btn-small pull-right'
  #address-info.address.modal.hide.fade
    .modal-body
      fieldset
        #map style="height: 200px; margin-bottom: 20px; border:  solid 1px #CCCCCC;"
          #map_canvas style="width: 100; height: 100;"
          = f.hidden_field :latitude, :class => 'address-latitude'
          = f.hidden_field :longitude, :class => 'address-longitude'
        .control-group
          label.control-label= f.label :member_address_type_id
          .controls
            = f.select :member_address_type_id, options_from_collection_for_select(MemberAddressType.all, 'id', 'name', f.object.member_address_type_id)
        .control-group
          label.control-label= f.label :address
          .controls
            = f.text_field :address, :placeholder => 'Россия, Москва', :class => 'address-input'
        .control-group
          label.control-label= f.label :note
          .controls
            = f.text_area :note, :rows => 5
        .control-group
          label.control-label= f.label :contacts
          .controls
            = f.text_field :contacts
        .control-group
          label.control-label= f.label :description
          .controls
            = f.text_area :description, :rows => 5
    .modal-footer
      a#save-btn.btn.btn-primary Сохранить
      a#cancel-btn.btn Отмена

app/views/control/members/_form.html.slim
= javascript_include_tag 'control/members'
script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGWSI8xlBZIb9GX1p_IqbgNKQbqXNpfBg&sensor=false" type="text/javascript"
#member
  = nested_form_for([:control, @member], :html => {:class => "form-horizontal"}) do |f|
    - if @member.errors.any?
      #error_explanation.alert.alert-error
        ul
          - @member.errors.full_messages.each do |msg|
            li= msg
    p#notice= notice
    .tabbable
      ul.nav.nav-tabs
        li.active
          a data-toggle="tab" href="#common-tab" Общее
        li
          a data-toggle="tab" href="#categories-tab" Категории
        li
          a data-toggle="tab" href="#regions-tab" Регионы
        li
          a data-toggle="tab" href="#addresses-tab" Адреса
        li
          a data-toggle="tab" href="#contacts-tab" Контакты
      .tab-content
        #common-tab.tab-pane.active
          fieldset
            .control-group
              label.control-label= f.label :name
              .controls
                = f.text_field :name
            .control-group
              label.control-label= f.label :member_tariff_id
              .controls
                = f.select :member_tariff_id, options_from_collection_for_select(MemberTariff.all, 'id', 'name', @member.member_tariff_id)
            .control-group
              label.control-label= f.label :is_moderated
              .controls
                = f.check_box :is_moderated
            .control-group
              label.control-label= f.label :user_id
              .controls
                = f.select :user_id, options_from_collection_for_select(User.all, :id, :full_name_with_email, @member.user_id), :include_blank => 'Не выбрано'
            .control-group
              label.control-label= f.label :country_id
              .controls
                = f.select :country_id, options_from_collection_for_select(Country.all, :id, :name, @member.country_id)
            .control-group
              label.control-label= f.label :image_id
              .controls
                = file_field_tag id: "member-logo-file"
                = hidden_field_tag :logo_id
                div
                  =image_tag @member.image.picture(:thumb), id: "member-logo" if @member.image
            .control-group
              label.control-label= f.label :description
              .controls
                = f.text_area :description, :rows => 10
        #categories-tab.tab-pane
          fieldset
            #categories
              - for category in MemberCategory.all
                .category
                  = check_box_tag "member[member_category_ids][]", category.id, @member.member_categories.include?(category)
                  = category.name
        #regions-tab.tab-pane
          fieldset
            #regions
              .list
                - if @member.regions.count > 0
                  - @member.regions.each do |region|
                    .region
                      = select_tag 'countries', options_from_collection_for_select(Country.all, :id, :name, region.country_id), :onchange => 'loadRegions(this)'
                      = select_tag "member[region_ids][]", options_from_collection_for_select(Region.all, :id, :name, region.id), :class => 'regions-select'
                      a.remove-region-btn.btn.btn-danger.btn-small Удалить
                - else
                  .region
                    = select_tag 'countries', options_from_collection_for_select(Country.all, :id, :name), :onchange => 'loadRegions(this)'
                    = select_tag "member[region_ids][]", options_from_collection_for_select(Region.all, :id, :name), :class => 'regions-select'
              a.btn onclick="Members.addRegion()" Добавить регион
        #addresses-tab.tab-pane
          fieldset
            #addresses
              .list
                = f.fields_for :member_addresses do |address_form|
                  = render '/control/members/address', :f => address_form
                = f.link_to_add "Добавить адрес", :member_addresses, :class => 'btn'
        #contacts-tab.tab-pane
          fieldset
            .control-group
              label.control-label= f.label :site
              .controls
                = f.text_field :site
            .control-group
              label.control-label= f.label :phone
              .controls
                = f.text_field :phone
            .control-group
              label.control-label= f.label :email
              .controls
                = f.text_field :email
            .control-group
              label.control-label= f.label :contacts
              .controls
                = f.text_area :contacts, :rows => 10
    .form-actions
      = f.submit 'Сохранить', :class => 'btn btn-primary'
      = link_to 'Отмена', control_members_path, :class => 'btn'

app/views/control/members/edit.html.slim
h1 Участники

= render 'form'

app/views/control/members/index.html.slim
h1 Участники
.table-control
  = link_to 'Добавить участника', new_control_member_path, :class => 'btn btn-primary'
table.table.table-striped.table-hover
  tr
    th= sortable :id, '#'
    th= sortable :name, 'Название'
    th= sortable :country_id, 'Страна'
    th= sortable :is_moderated, 'Модерирован'
    th= sortable :site, 'Сайт'
    th= sortable :phone, 'Телефон'
    th= sortable :email, 'Email'
    th
  - @members.each do |member|
    tr class="#{'success' if member.is_moderated}"
      td
        strong= member.id
      td= member.name
      td= member.country.name if member.country
      td= member.is_moderated ? 'Да' : 'Нет'
      td
        = link_to member.site, "http://#{member.site}"
      td= member.phone
      td
        = link_to member.email, "mailto:#{member.email}"
      td.text-right
        = link_to 'Изменить', edit_control_member_path(member), :class => 'btn btn-small'
        = link_to 'Удалить', control_member_path(member), method: :delete, data: { confirm: 'Вы уверены?' }, :class => 'btn btn-danger btn-small'
= will_paginate @members, :renderer => BootstrapPagination::Rails

app/views/control/members/new.html.slim
h1 Участники

= render 'form'