config/routes.rb
Plants::Application.routes.draw do

  root :to => 'root#index'

  get 'profile' => 'profile#me'
  get 'profile/member'
  get 'profile/catalog'
  put 'profile/update_member'
  post 'profile/update_member'
  put 'profile/update_me'
  post 'profile/update_me'
  get 'profile/new_price'
  put 'profile/save_price'
  post 'profile/save_price'
  put 'profile/update_plant_price'
  post 'profile/update_plant_price'
  post 'profile/remove_plant_price'
  delete 'profile/remove_member_price'

  devise_for :users, :path => "auth", :path_names => {:sign_in => 'login',
                                                      :sign_out => 'logout',
                                                      :password => 'secret',
                                                      :confirmation => 'verification',
                                                      :unlock => 'unblock',
                                                      :registration => 'register',
                                                      :sign_up => 'cmon_let_me_in'},
             :controllers => {:registrations => "registrations"}


  resources :members
  resources :plants
  resources :images

  namespace :control do

    root :to => 'users#index'

    resources :members
    resources :plants
    resources :users
    resources :member_categories
    resources :regions
    resources :countries
    resources :plant_categories
    resources :plant_features
    resources :genus
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  belongs_to :member_tariff
  has_one :image, :foreign_key => :owner_id
  has_and_belongs_to_many :member_categories

  has_and_belongs_to_many :regions
  accepts_nested_attributes_for :regions

  has_many :member_addresses, :dependent => :delete_all
  accepts_nested_attributes_for :member_addresses, :allow_destroy => true

  has_many :member_prices
  accepts_nested_attributes_for :member_prices, :allow_destroy => true

  has_many :plant_prices
  accepts_nested_attributes_for :plant_prices, :allow_destroy => true

  attr_accessible :contacts, :description, :email, :is_moderated, :name, :phone, :site
  attr_accessible :user_id, :country_id, :image_id
  attr_accessible :member_tariff_id

  attr_accessible :region_ids
  attr_accessible :member_category_ids
  attr_accessible :member_addresses_attributes
  attr_accessible :member_addresses
  attr_accessible :prices
  attr_accessible :prices_attributes
  attr_accessible :plant_prices
  attr_accessible :plant_prices_attributes

  validates :name, :presence => true, :uniqueness => true

  scope :moderated, lambda { where(:is_moderated => true) }

end

app/controllers/control/members_controller.rb
module Control
  class MembersController < ControlPanelController

    after_filter :update_member_logo, :only => [:create, :update]

    # GET /members
    # GET /members.json
    def index
      @members = Member.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @members }
      end
    end

    # GET /members/1
    # GET /members/1.json


    # GET /members/new
    # GET /members/new.json
    def new
      @member = Member.new
      @member.regions.build

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @member }
      end
    end

    # GET /members/1/edit
    def edit
      @member = Member.find(params[:id])
    end

    # POST /members
    # POST /members.json
    def create

      @member = Member.new(params[:member])

      respond_to do |format|
        if @member.save
          format.html { redirect_to control_members_path,
                                    notice: t('activerecord.attributes.member.messages.has_been_success_created') }
          format.json { render json: @member, status: :created, location: @member }
        else
          format.html { render action: "new" }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /members/1
    # PUT /members/1.json
    def update

      @member = Member.find(params[:id])

      respond_to do |format|
        if @member.update_attributes(params[:member])
          format.html { redirect_to control_members_path,
                                    notice: t('activerecord.attributes.member.messages.has_been_success_updated') }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /members/1
    # DELETE /members/1.json
    def destroy
      @member = Member.find(params[:id])
      @member.destroy

      respond_to do |format|
        format.html { redirect_to control_members_path }
        format.json { head :no_content }
      end
    end

    private

    def update_member_logo
      return if params[:logo_id].blank?

      old_images = Image.where(:owner_id => @member.id)
      old_images.delete_all

      image = Image.find(params[:logo_id])
      image.owner_id = @member.id
      image.save
    end

  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.moderated
    @members = @members.where('members.name LIKE ?', "%#{params[:search]}%") unless params[:search].blank?
    unless params[:region_id].blank?
      @members = @members.joins(:regions).where('regions.id = ?', params[:region_id])
      @members = @members.group('members.id')
    end
    @members = @members.paginate(:page => params[:page])
  end

  def show
    @member = Member.moderated.find(params[:id])
    if params[:modal]
      render 'show', :layout => false
    end
  end

end

app/helpers/members_helper.rb
module MembersHelper

  def member_title(member)
    title = member.name
    member.member_categories.each do |c|
      title += ", #{c.name}"
    end
    title
  end

  def categories_string(member)
    categories = ''
    member.member_categories.each do |c|
      categories += " #{c.name},"
    end
    categories.chop
  end

end

app/views/members/index.html.slim
= content_for :title, 'Участники'
script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGWSI8xlBZIb9GX1p_IqbgNKQbqXNpfBg&sensor=false" type="text/javascript"
= content_for :search do
  form action=members_path method="get"
    .well.sidebar-nav style="margin-top: 90px;"
      ul.nav.nav-list
        li.nav-header Поиск
        li
          p
            = text_field_tag :search, params[:search], :placeholder => 'Поиск'
        li
          p
            = select_tag :country_id, options_from_collection_for_select(Country.all, :id, :name, params[:country_id]), :prompt => 'Все', :onchange => 'loadRegions(this, "#region_id")'
        li
          p
            - regions = []
            - regions = Region.where(:country_id => params[:country_id]) if params[:country_id]
            = select_tag :region_id, options_from_collection_for_select(regions, :id, :name, params[:region_id]), :prompt => 'Все'
        li
          = submit_tag 'Поиск', :class => 'btn btn-primary', :name => nil
          = button_tag 'Сбросить', :class => 'btn', :name => nil, :type => 'reset'
h1 Участники
#members
  - if @members.empty?
    p Поиск не дал результатов, попробуйте выбрать другие критерии поиска.
  - @members.each do |member|
    .member
      = hidden_field_tag :id, member.id
      div style="float: left"
        h4
          = link_to member_title(member), member_path(member), :target => '_blank'
        .info
          .description
            = member.description
          .addresses
            strong Адреса:
            - member.member_addresses.each do |address|
              = "#{address.address};"
          .phone
            = member.phone
          .site
            = link_to member.site, "http://#{member.site}", :target => '_blank'
      .logo
        / = link_to member_path(member), :target => '_blank' do
          = image_tag(member.image.picture(:thumb))
      div style="clear: both"
      .links
        a.btn.btn-small href="javascript:" onclick="showOnMap(this)" Развернуть
      #details
        .modal class="hide fade"
          .modal-body style="max-height: 470px;"
            button.close aria-hidden="true" data-dismiss="modal" type="button" ×
            #details-content
          .modal-footer
            a.btn data-dismiss="modal" Закрыть
            = link_to 'Открыть в номом окне', member_path(member), :target => '_blank', :class => 'btn btn-primary'
  = will_paginate @members, :renderer => BootstrapPagination::Rails

app/views/members/show.html.slim
= content_for :title, @member.name
= javascript_include_tag :member
#member
  div
    .logo
      = image_tag(@member.image.picture(:thumb)) if @member.image.present?
    h1= @member.name
    strong= @member.country.name
    div style="clear: both;"
  hr
  h4 О нас
  dl.info.dl-horizontal
    dt Категории:
    dd
      = categories_string(@member)
    dt Описание:
    dd
      = @member.description
    dt Регионы:
    dd
      - @member.regions.each do |region|
        = region.name
        | (
        b= region.country.name
        | )
        br
  hr
  h4 Контакты
  dl.info.dl-horizontal
    dt Телефон:
    dd
      span.phone= @member.phone
    dt Сайт:
    dd
      = link_to @member.site, "http://#{@member.site}", :target => '_blank'
    dt E-mail:
    dd
      = link_to @member.email, "mailto:#{@member.email}"
    dt Контакты:
    dd
      = @member.contacts
  hr
  h4 Наши адреса
  #addresses
    script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGWSI8xlBZIb9GX1p_IqbgNKQbqXNpfBg&sensor=false" type="text/javascript"
    #map_canvas
    - @member.member_addresses.each_with_index do |address, index|
      .address
        hr
        div
          p
            a.show-on-map-link href="javascript:"
              = index + 1
              | . #{address.member_address_type.name}
              | (#{@member.name})
          p
            strong Адрес:
            = address.address
          - unless address.contacts.blank?
            p
              strong Контакты:
              = address.contacts
          - unless address.note.blank?
            p
              strong Примечание:
              = address.note
        = hidden_field_tag :latitude, address.latitude
        = hidden_field_tag :longitude, address.longitude
        .map-bubble-wrapper
          .map-bubble
            strong
              = address.member_address_type.name
              | (#{@member.name})
            hr
            p
              strong Адрес:
              = address.address
            - unless address.contacts.blank?
              p
                strong Контакты:
                = address.contacts
            - unless address.note.blank?
              p
                strong Примечание:
                = address.note

app/views/members/show.js.erb
$(function () {

    var canvas = $('#map_canvas').get(0);
    var map = new google.maps.Map(canvas, { zoom: 10, mapTypeId: google.maps.MapTypeId.ROADMAP });

    var addresses = [];
    <% @member.member_addresses.each do |address| %>
    addresses.push({
            lat: <%= address.latitude %>,
            lon: <%= address.longitude %>
        });
    <% end %>

    $.each(addresses, function(index, address) {

        var pos = new google.maps.LatLng(address.lat, address.lon);
        var marker = new google.maps.Marker({ map: map, position: pos });
        console.log('1');
    });

    setTimeout(function () {
        google.maps.event.trigger(canvas, 'resize');
        //map.panTo(center);

    }, 1000);

    alert(1);
});